### PR TITLE
massive config parsing improvement that improves the parsing of confi…

### PR DESCRIPTION
**Pull request by syricium**
…g?!?

### CODE REVIEW

**Review by cyrus01337 — COMMENTED** [review]
This can be simplified by removing it.

**Comment by syricium** [comment]
> This can be simplified by removing it.

removingh what?

**Comment by Ender2K89** [comment]
Hello syrice,

submitting troll pull requests (pull requests with intentionally problematic or irrelevant code changes) is not a productive or professional behavior in the software development community. It can have negative consequences for both the individual who submitted the pull request and the project as a whole.

First and foremost, submitting troll pull requests wastes the time and resources of the project maintainers and other contributors. Reviewing and addressing these requests takes time and effort away from more meaningful work, and can even slow down the progress of the project. This can also cause frustration for other contributors who are trying to make valuable contributions to the project.

Additionally, submitting troll pull requests can damage the reputation of the individual who submitted the request. The software development community is built on trust, collaboration, and mutual respect, and submitting troll pull requests goes against these core values. This can hurt the individual's credibility and make it harder for them to participate in other projects or be taken seriously in the future.

Finally, submitting troll pull requests can also harm the reputation of the project as a whole. Projects that are known for tolerating this kind of behavior can be seen as unprofessional and less credible, which can make it harder for them to attract new contributors or users.

In conclusion, submitting troll pull requests is a counterproductive and unprofessional behavior that should be avoided. It wastes the time and resources of others, damages the reputation of the individual and the project, and goes against the core values of the software development community. Instead of submitting troll pull requests, individuals should focus on making meaningful contributions that advance the project and the community as a whole.

Sincerely yours,
Ender

**Comment by syricium** [comment]
> Hello syrice,
> 
> submitting troll pull requests (pull requests with intentionally problematic or irrelevant code changes) is not a productive or professional behavior in the software development community. It can have negative consequences for both the individual who submitted the pull request and the project as a whole.
> 
> First and foremost, submitting troll pull requests wastes the time and resources of the project maintainers and other contributors. Reviewing and addressing these requests takes time and effort away from more meaningful work, and can even slow down the progress of the project. This can also cause frustration for other contributors who are trying to make valuable contributions to the project.
> 
> Additionally, submitting troll pull requests can damage the reputation of the individual who submitted the request. The software development community is built on trust, collaboration, and mutual respect, and submitting troll pull requests goes against these core values. This can hurt the individual's credibility and make it harder for them to participate in other projects or be taken seriously in the future.
> 
> Finally, submitting troll pull requests can also harm the reputation of the project as a whole. Projects that are known for tolerating this kind of behavior can be seen as unprofessional and less credible, which can make it harder for them to attract new contributors or users.
> 
> In conclusion, submitting troll pull requests is a counterproductive and unprofessional behavior that should be avoided. It wastes the time and resources of others, damages the reputation of the individual and the project, and goes against the core values of the software development community. Instead of submitting troll pull requests, individuals should focus on making meaningful contributions that advance the project and the community as a whole.
> 
> Sincerely yours, Ender

ily frfr

**Comment by cyrus01337** [comment]
What he said. Lol.

**Comment by cyrus01337** [comment]
I mean I didn't read it but yeah what he said.

**Pull request closed without merging**
